name: Setup
description: Setup project

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3

    - name: Install dependencies
      run: npm ci
      shell: bash # workflowsでは必要ないがcompositeでは必要になる

    - name: Check lint
      run: npm run lint
      shell: bash

    - name: Run build
      run: npm run build
      shell: bash
