name: composite hello action
description: ログアクションを共通化する
inputs:
  target:
    description: あなたが挨拶したいのは誰ですか？
outputs:
  target:
    value: ${{ inputs.target }}
    description: 挨拶した相手

runs:
  using: composite
  steps:
    - run: echo "Hello, ${TARGET}!"
      shell: bash
      env:
        TARGET: ${{ inputs.target }}
