name: dispatch-slack-incoming-webhook

on:
  workflow_dispatch:

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification with auto merge enabled
        if: github.ref == 'refs/heads/main'
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        with:
          channel-id: 'C05BZT995K8'
          payload: |
            {
              "text": "(ref: ${{ github.ref }}) :warning: \n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "(ref: ${{ github.ref }}) :warning: \n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
