name: pull-request-branch-cleanup

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: branch-cleanup-action
    runs-on: ubuntu-latest
    steps:
      - name: branch-cleanup
        uses: jessfraz/branch-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
