# name: pull-request-assign-author

# on:
#   pull_request:
#     types: [opened]
# jobs:
#   assign-author:
#     if: ${{ ! contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
#     permissions:
#       issues: write
#       pull-requests: write
#     runs-on: ubuntu-latest
#     steps:
#       - uses: technote-space/assign-author@v1

# 上記のactionsを使用したworkflowでも問題ない

on:
  pull_request:
    types: [opened, ready_for_review]

# @see https://docs.github.com/ja/rest/issues/assignees?apiVersion=2022-11-28#add-assignees-to-an-issue
# addAssigneesする場合はpermissions: writeが必要になる
permissions: write-all

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/add-assignees.js')
            await script({github, context, core})

  notification-with-slack-github-action:
    uses: ./.github/workflows/reusable_slack_github_action.yml
    with:
      name: 1zushun
