# name: pull-request-assign-author

# on:
#   pull_request:
#     types: [opened]
# jobs:
#   assign-author:
#     if: ${{ ! contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
#     permissions:
#       issues: write
#       pull-requests: write
#     runs-on: ubuntu-latest
#     steps:
#       - uses: technote-space/assign-author@v1

# おそらく下記でも動くはず
on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/add-assignees.js')
            await script({github, context, core})
