on:
  pull_request:
    types: [opened, ready_for_review, reopened]

permissions: write-all

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/post-comment.js')
            await script({github, context, core})
