on:
  pull_request:
    types: [ready_for_review]

# @see https://docs.github.com/ja/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment
# createCommentする場合はpermissions: writeが必要になる
permissions: write-all

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/create-comment.js')
            await script({github, context, core})
