on: push

# https://swfz.hatenablog.com/entry/2020/04/18/160235
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT 
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    # needsでjob1のoutputを参照できたらoutput2の値が表示される
    # jobを跨いで参照する場合は一度マッピングする必要がある
    # stepの場合は不要
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}