name: push-build-with-actions

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Volta Actions
        uses: ./.github/actions/setupVolta/
