# https://book.st-hakky.com/hakky/github-actions-result-notification-to-slack/
on: workflow_call

name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_ICON_EMOJI: bell