name: push-say-with-workflow-call

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.name }}."

  bye:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bye, ${{ inputs.name }}."
